1. Matrix Operations
   
What is a Matrix?
A matrix is a rectangular array of numbers arranged in rows and columns. Matrices are fundamental in linear algebra, and they are widely used in AI, ML, and data science.

Basic Matrix Operations
Addition & Subtraction
If 𝐴and 𝐵 are matrices of the same size: 𝐶=𝐴+𝐵,𝐷=A−𝐵

Scalar Multiplication
Each element of the matrix is multiplied by a constant 𝑘:𝐵=𝑘𝐴

Matrix Multiplication
If 𝐴 has dimensions 𝑚×𝑛 and 𝐵 has 𝑛×𝑝, their product 𝐶 is:𝐶=𝐴×𝐵

Transpose of a Matrix
The transpose of 𝐴 is obtained by flipping its rows and columns:𝐴^𝑇
 
Determinant & Inverse of a Matrix
A matrix is invertible if its determinant is non-zero.The inverse is given by: 

𝐴^(−1)=(1/det(𝐴))*adj(A)

Eigenvalues and Eigenvectors

An eigenvector of a matrix is a vector that, when multiplied by the matrix, does not change its direction, only its magnitude.

The eigenvalue is the factor by which the eigenvector is scaled.

Mathematically, if A is a square matrix and v is a vector, then:

𝐴𝑣=𝜆𝑣

where:

𝑣 is the eigenvector,
𝜆(lambda) is the eigenvalue and
𝐴 is the given matrix

  
2. Gradient Calculations

 What is a Gradient?
The gradient of a function represents the direction and rate of the steepest increase. It is a key concept in calculus, optimization, and deep learning.

For a function 
𝑓(𝑥,𝑦), the gradient is a vector of partial derivatives:

∇𝑓=(∂𝑓/∂𝑥,∂𝑓/∂𝑦) (This is symbolic differentiation)

In machine learning, the gradient is used in gradient descent, where model parameters are updated iteratively:

𝑤=𝑤−𝛼∇𝑓(𝑤)

where:

𝑤= parameters (weights)
𝛼= learning rate
∇𝑓(𝑤)= gradient of the loss function

Numerical Gradient Approximation
When an analytical gradient is difficult to compute, we approximate it using the finite difference method:

𝑓′(𝑥) ≈ (𝑓(𝑥+ℎ)−𝑓(𝑥−ℎ))/2ℎ,ℎ is a small step size (e.g., ℎ=1𝑒−5=10^(-5)) (This is numerical  differentiation)


In [1]:
#Matrix operations
import numpy as np

# Define two complex matrices
A = np.array([[12, -7], [5, 19]])
B = np.array([[87, 23], [-4, 11]])

# Matrix Addition
addition = A + B
print("Matrix Addition:\n", addition)

# Matrix Subtraction
subtraction = A - B
print("\nMatrix Subtraction:\n", subtraction)

# Matrix Multiplication (Dot Product)
multiplication = np.dot(A, B)
print("\nMatrix Multiplication:\n", multiplication)

# Determinant of A
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

# Inverse of A
if det_A != 0:  # Check if the determinant is non-zero
    inverse_A = np.linalg.inv(A)
    print("\nInverse of A:\n", inverse_A)
else:
    print("\nMatrix A is singular and cannot be inverted.")

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)


Matrix Addition:
 [[99 16]
 [ 1 30]]

Matrix Subtraction:
 [[-75 -30]
 [  9   8]]

Matrix Multiplication:
 [[1072  199]
 [ 359  324]]

Determinant of A: 263.00000000000006

Inverse of A:
 [[ 0.07224335  0.02661597]
 [-0.01901141  0.04562738]]

Eigenvalues of A: [15.5+4.76969601j 15.5-4.76969601j]

Eigenvectors of A:
 [[ 0.76376262+0.j         0.76376262-0.j       ]
 [-0.38188131-0.5204165j -0.38188131+0.5204165j]]


In [2]:
# This program calculates gradients (derivatives) of a function using symbolic differentiation.

import sympy as sp
'''SymPy is a Python library for symbolic mathematics. Unlike NumPy, which deals with numerical computations, SymPy performs symbolic calculations, meaning it manipulates mathematical expressions just like you would on paper.

# Define the variables
x, y = sp.symbols('x y')

# Define the function f(x, y)
f = 7*x**2 + 13*y**2 -8*x*y - 41*x + 59

# Compute the gradient (partial derivatives)
grad_x = sp.diff(f, x)  # Partial derivative w.r.t x
grad_y = sp.diff(f, y)  # Partial derivative w.r.t y

print("\nGradient of f:")
print("∂f/∂x =", grad_x)
print("∂f/∂y =", grad_y)

# Evaluate the gradient at (x=1, y=2)
grad_at_point = {x: 1, y: 2}
grad_x_val = grad_x.evalf(subs=grad_at_point)
grad_y_val = grad_y.evalf(subs=grad_at_point)

print("\nGradient at (x=1, y=2):")
print(f"∂f/∂x = {grad_x_val}, ∂f/∂y = {grad_y_val}")



Gradient of f:
∂f/∂x = 14*x - 8*y - 41
∂f/∂y = -8*x + 26*y

Gradient at (x=1, y=2):
∂f/∂x = -43.0000000000000, ∂f/∂y = 44.0000000000000


In [4]:
# functions where symbolic differentiation is hard, we use numerical differentiation.

import numpy as np

# Define function
def f(x):
    return 12*x**3 - 41*x**2 + 32*x + 19  # Example function

# Numerical derivative using finite differences
def numerical_derivative(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

# Compute gradient at x=2
grad_value = numerical_derivative(f, 2)
print("\nNumerical Gradient at x=2:", grad_value)



Numerical Gradient at x=2: 12.000000001677334
